package ini.ast;

import ini.type.Type;

import java.io.PrintStream;

public interface AstNode {

	int NODE = 0;
	int ARRAY_ACCESS = NODE + 1;
	int ASSIGNMENT = ARRAY_ACCESS + 1;
	int AT_BINDING = ASSIGNMENT + 1;
	int AT_PREDICATE = AT_BINDING + 1;
	int BINARY_OPERATOR = AT_PREDICATE + 1;
	int BINDING = BINARY_OPERATOR + 1;
	int BOOLEAN_LITERAL = BINDING + 1;
	int CASE_STATEMENT = BOOLEAN_LITERAL + 1;
	int CHAR_LITERAL = CASE_STATEMENT + 1;
	int CONSTRUCTOR = CHAR_LITERAL + 1;
	int CONSTRUCTOR_MATCH_EXPRESSION = CONSTRUCTOR + 1;
	int FIELD_ACCESS = CONSTRUCTOR_MATCH_EXPRESSION + 1;
	int FUNCTION = FIELD_ACCESS + 1;
	int FUNCTION_LITERAL = FUNCTION + 1;
	int IMPORT = FUNCTION_LITERAL + 1;
	int INVOCATION = IMPORT + 1;
	int LIST_EXPRESSION = INVOCATION + 1;
	int NUMBER_LITERAL = LIST_EXPRESSION + 1;
	int PARAMETER = NUMBER_LITERAL + 1;
	int RETURN_STATEMENT = PARAMETER + 1;
	int RULE = RETURN_STATEMENT + 1;
	int SET_CONSTRUCTOR = RULE + 1;
	int SET_DECLARATION = SET_CONSTRUCTOR + 1;
	int SET_EXPRESSION = SET_DECLARATION + 1;
	int STRING_LITERAL = SET_EXPRESSION + 1;
	int SUB_ARRAY_ACCESS = STRING_LITERAL + 1;
	int THIS_LITERAL = SUB_ARRAY_ACCESS + 1;
	int UNARY_OPERATOR = THIS_LITERAL + 1;
	int USER_TYPE = UNARY_OPERATOR + 1;
	int VARIABLE = USER_TYPE + 1;

	void prettyPrint(PrintStream out);

	int nodeTypeId();

	Token token();

	Type getType();

	void setType(Type type);
}
