
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Aug 17 09:20:28 CEST 2019
//----------------------------------------------------

package ini.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RSPAREN = 11;
  public static final int PLUSPLUS = 24;
  public static final int FUNCTION = 47;
  public static final int LTE = 13;
  public static final int MULT = 19;
  public static final int CHAR = 39;
  public static final int EQUALS = 17;
  public static final int CASE = 53;
  public static final int LPAREN = 6;
  public static final int INT = 34;
  public static final int MINUS = 21;
  public static final int RPAREN = 7;
  public static final int OROR = 25;
  public static final int NOT = 28;
  public static final int AND = 27;
  public static final int LT = 12;
  public static final int TYPE = 51;
  public static final int COMMA = 3;
  public static final int TUBE = 29;
  public static final int IMPLIES = 30;
  public static final int DOTDOT = 5;
  public static final int DIV = 20;
  public static final int ANDAND = 26;
  public static final int NUM = 35;
  public static final int PLUS = 23;
  public static final int ASSIGN = 16;
  public static final int THIS = 52;
  public static final int PROCESS = 48;
  public static final int LF = 44;
  public static final int DOT = 4;
  public static final int OF = 49;
  public static final int EOF = 0;
  public static final int RETURN = 50;
  public static final int MINUSMINUS = 22;
  public static final int MATCHES = 31;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int GTE = 14;
  public static final int IMPORT = 46;
  public static final int COL = 2;
  public static final int TIDENTIFIER = 41;
  public static final int ARROW_RIGHT = 33;
  public static final int LCPAREN = 8;
  public static final int RCPAREN = 9;
  public static final int NOTEQUALS = 18;
  public static final int DOLLAR = 43;
  public static final int DEFAULT = 54;
  public static final int END = 45;
  public static final int QUESTION = 42;
  public static final int STRING = 38;
  public static final int AT = 32;
  public static final int FALSE = 37;
  public static final int GT = 15;
  public static final int LSPAREN = 10;
  public static final int IDENTIFIER = 40;
}

