
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 01 08:57:07 CEST 2019
//----------------------------------------------------

package ini.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RSPAREN = 12;
  public static final int PLUSPLUS = 25;
  public static final int FUNCTION = 48;
  public static final int LTE = 14;
  public static final int MULT = 20;
  public static final int CHAR = 40;
  public static final int INVDOT = 5;
  public static final int EQUALS = 18;
  public static final int CASE = 55;
  public static final int LPAREN = 7;
  public static final int CHANNEL = 59;
  public static final int INT = 35;
  public static final int MINUS = 22;
  public static final int RPAREN = 8;
  public static final int OROR = 26;
  public static final int NOT = 29;
  public static final int AND = 28;
  public static final int LT = 13;
  public static final int TYPE = 53;
  public static final int COMMA = 3;
  public static final int TUBE = 30;
  public static final int IMPLIES = 31;
  public static final int DOTDOT = 6;
  public static final int DIV = 21;
  public static final int ANDAND = 27;
  public static final int NUM = 36;
  public static final int PLUS = 24;
  public static final int ASSIGN = 17;
  public static final int THIS = 54;
  public static final int PROCESS = 49;
  public static final int LF = 45;
  public static final int DOT = 4;
  public static final int OF = 51;
  public static final int EOF = 0;
  public static final int RETURN = 52;
  public static final int MINUSMINUS = 23;
  public static final int MATCHES = 32;
  public static final int TRUE = 37;
  public static final int LAMBDA = 50;
  public static final int error = 1;
  public static final int PREDICATE = 60;
  public static final int DECLARE = 58;
  public static final int GTE = 15;
  public static final int IMPORT = 47;
  public static final int COL = 2;
  public static final int TIDENTIFIER = 42;
  public static final int ARROW_RIGHT = 34;
  public static final int ELSE = 57;
  public static final int LCPAREN = 9;
  public static final int RCPAREN = 10;
  public static final int NOTEQUALS = 19;
  public static final int DOLLAR = 44;
  public static final int DEFAULT = 56;
  public static final int END = 46;
  public static final int QUESTION = 43;
  public static final int STRING = 39;
  public static final int AT = 33;
  public static final int FALSE = 38;
  public static final int GT = 16;
  public static final int LSPAREN = 11;
  public static final int IDENTIFIER = 41;
}

