/* The following code was generated by JFlex 1.4 on 8/2/19 5:43 PM */


/*
 * This source code file is the exclusive property of its author. No copy or 
 * usage of the source code is permitted unless the author contractually 
 * allows it under the terms of a well-defined agreement.
 */

package ini.parser;

import java_cup.runtime.*;
import ini.ast.Token;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4
 * on 8/2/19 5:43 PM from the specification file
 * <tt>ini.lex</tt>
 */
class IniScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int CHAR = 3;
  public static final int BLOCK = 1;
  public static final int BBLOCK = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\53\1\5"+
    "\1\0\1\57\1\0\1\60\1\63\1\42\1\43\1\7\1\61\1\52"+
    "\1\37\1\15\1\6\1\13\11\14\1\41\1\0\1\50\1\51\1\40"+
    "\1\56\1\62\32\12\1\46\1\4\1\47\1\0\1\11\1\0\1\32"+
    "\1\10\1\27\1\36\1\30\1\24\1\10\1\35\1\16\2\10\1\33"+
    "\1\17\1\26\1\21\1\20\1\10\1\22\1\31\1\23\1\25\3\10"+
    "\1\34\1\10\1\44\1\55\1\45\1\54\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\0\1\2\2\3\1\4\1\5\1\6"+
    "\1\7\1\10\2\11\1\12\10\7\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\1\1\40\1\1\2\41\1\42\3\0"+
    "\1\43\2\7\1\44\10\7\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\2\0\2\57"+
    "\12\7\2\0\3\7\1\60\1\61\1\62\2\7\1\63"+
    "\1\7\1\0\4\7\1\64\1\7\1\65\1\7\1\66"+
    "\2\7\1\67\1\7\1\70\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\320\0\u0138"+
    "\0\u016c\0\320\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\320\0\320\0\320\0\320\0\320\0\320\0\320"+
    "\0\u04ac\0\u04e0\0\320\0\u0514\0\320\0\u0548\0\320\0\320"+
    "\0\u057c\0\u05b0\0\320\0\320\0\u05e4\0\320\0\u0618\0\320"+
    "\0\u064c\0\320\0\u0680\0\u06b4\0\u06e8\0\320\0\u071c\0\u0750"+
    "\0\u01a0\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc"+
    "\0\u08f0\0\320\0\320\0\320\0\320\0\320\0\320\0\320"+
    "\0\320\0\320\0\320\0\u0924\0\u0958\0\320\0\u098c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60"+
    "\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u01a0\0\u01a0"+
    "\0\u01a0\0\u0ccc\0\u0d00\0\u01a0\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0"+
    "\0\u0e04\0\u0e38\0\u01a0\0\u0e6c\0\u01a0\0\u0ea0\0\u01a0\0\u0ed4"+
    "\0\u0f08\0\u01a0\0\u0f3c\0\u01a0\0\u01a0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\2\7\1\5\1\10\1\11\1\12\1\13"+
    "\1\5\1\14\1\15\1\16\1\17\1\20\1\13\1\21"+
    "\1\22\1\23\1\24\1\25\2\13\1\26\6\13\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\64\5\2\55\1\56"+
    "\1\55\1\57\1\56\56\55\2\60\1\56\1\60\1\61"+
    "\56\60\1\56\66\0\1\7\66\0\1\62\64\0\1\63"+
    "\1\64\64\0\5\13\1\0\21\13\35\0\5\14\1\0"+
    "\21\14\42\0\1\65\61\0\2\16\1\65\63\0\1\66"+
    "\56\0\5\13\1\0\1\13\1\67\17\13\35\0\5\13"+
    "\1\0\4\13\1\70\14\13\35\0\5\13\1\0\6\13"+
    "\1\71\12\13\35\0\5\13\1\0\12\13\1\72\6\13"+
    "\35\0\5\13\1\0\4\13\1\73\11\13\1\74\1\75"+
    "\1\13\35\0\5\13\1\0\7\13\1\76\4\13\1\77"+
    "\4\13\35\0\5\13\1\0\14\13\1\100\4\13\35\0"+
    "\5\13\1\0\12\13\1\101\6\13\64\0\1\102\1\103"+
    "\74\0\1\104\63\0\1\105\52\0\1\106\10\0\1\107"+
    "\63\0\1\110\67\0\1\111\66\0\1\112\64\0\1\113"+
    "\2\0\2\55\1\0\1\55\1\57\1\0\60\55\1\0"+
    "\1\55\1\57\57\55\63\0\1\60\1\63\1\6\1\7"+
    "\61\63\7\114\1\115\54\114\13\0\1\116\1\117\57\0"+
    "\5\13\1\0\2\13\1\120\16\13\35\0\5\13\1\0"+
    "\3\13\1\121\15\13\35\0\5\13\1\0\5\13\1\122"+
    "\13\13\35\0\5\13\1\0\7\13\1\123\11\13\35\0"+
    "\5\13\1\0\2\13\1\124\16\13\35\0\5\13\1\0"+
    "\1\125\20\13\35\0\5\13\1\0\10\13\1\126\10\13"+
    "\35\0\5\13\1\0\15\13\1\127\3\13\35\0\5\13"+
    "\1\0\13\13\1\130\5\13\35\0\5\13\1\0\6\13"+
    "\1\131\12\13\25\0\7\114\1\132\54\114\7\115\1\133"+
    "\54\115\13\0\2\117\57\0\5\13\1\0\3\13\1\134"+
    "\15\13\35\0\5\13\1\0\11\13\1\135\7\13\35\0"+
    "\5\13\1\0\7\13\1\136\11\13\35\0\5\13\1\0"+
    "\12\13\1\137\6\13\35\0\5\13\1\0\12\13\1\140"+
    "\6\13\35\0\5\13\1\0\13\13\1\141\5\13\35\0"+
    "\5\13\1\0\11\13\1\142\7\13\35\0\5\13\1\0"+
    "\13\13\1\143\5\13\35\0\5\13\1\0\12\13\1\144"+
    "\6\13\35\0\5\13\1\0\14\13\1\145\4\13\25\0"+
    "\6\114\1\7\1\132\54\114\6\115\1\7\1\146\54\115"+
    "\10\0\5\13\1\0\4\13\1\147\14\13\35\0\5\13"+
    "\1\0\12\13\1\150\6\13\35\0\5\13\1\0\4\13"+
    "\1\151\14\13\35\0\5\13\1\0\5\13\1\152\13\13"+
    "\35\0\5\13\1\0\12\13\1\153\6\13\35\0\5\13"+
    "\1\0\7\13\1\154\11\13\25\0\6\115\1\0\1\146"+
    "\54\115\10\0\5\13\1\0\5\13\1\155\13\13\35\0"+
    "\5\13\1\0\13\13\1\156\5\13\35\0\5\13\1\0"+
    "\10\13\1\157\10\13\35\0\5\13\1\0\1\160\20\13"+
    "\35\0\5\13\1\0\15\13\1\161\3\13\35\0\5\13"+
    "\1\0\13\13\1\162\5\13\35\0\5\13\1\0\3\13"+
    "\1\163\15\13\35\0\5\13\1\0\5\13\1\164\13\13"+
    "\35\0\5\13\1\0\10\13\1\165\10\13\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3952];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\0\1\11\1\1\1\11\2\1\1\11"+
    "\17\1\7\11\2\1\1\11\1\1\1\11\1\1\2\11"+
    "\2\1\2\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\3\0\1\11\13\1\12\11\2\0\1\11\13\1\2\0"+
    "\12\1\1\0\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	//StringBuffer string=new StringBuffer();
	String fileName;
	public void setFileName(String name) {
		fileName=name;
	}
	public String getFileName() {
		return fileName;
	}
	private Symbol symbol(int type) {
		return new Symbol(type,yyline,yycolumn,
		    new Token(type,fileName,yytext(),
		                    yyline+1,yycolumn+1,
		                    yycolumn+1+yytext().length()));
	}
	private Symbol emptyString() {
		return new Symbol(sym.STRING,yyline,yycolumn,
		    new Token(sym.STRING,fileName,"",
		                    yyline+1,yycolumn+1,
		                    yycolumn+1+0));
	}
	//private Symbol symbol(int type,Object value) {
	//	return new Symbol(type,yyline,yycolumn,value);
	//}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  IniScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  IniScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { /* ignore */
          }
        case 58: break;
        case 36: 
          { return symbol(sym.OF);
          }
        case 59: break;
        case 15: 
          { return symbol(sym.RPAREN);
          }
        case 60: break;
        case 17: 
          { return symbol(sym.RCPAREN);
          }
        case 61: break;
        case 12: 
          { return symbol(sym.GT);
          }
        case 62: break;
        case 27: 
          { return symbol(sym.DOLLAR);
          }
        case 63: break;
        case 20: 
          { return symbol(sym.LT);
          }
        case 64: break;
        case 55: 
          { return symbol(sym.PROCESS);
          }
        case 65: break;
        case 13: 
          { return symbol(sym.COL);
          }
        case 66: break;
        case 9: 
          { return symbol(sym.INT);
          }
        case 67: break;
        case 23: 
          { return symbol(sym.NOT);
          }
        case 68: break;
        case 28: 
          { return symbol(sym.AND);
          }
        case 69: break;
        case 37: 
          { return symbol(sym.MINUSMINUS);
          }
        case 70: break;
        case 21: 
          { return symbol(sym.ASSIGN);
          }
        case 71: break;
        case 5: 
          { return symbol(sym.DIV);
          }
        case 72: break;
        case 38: 
          { return symbol(sym.ARROW_RIGHT);
          }
        case 73: break;
        case 42: 
          { return symbol(sym.EQUALS);
          }
        case 74: break;
        case 54: 
          { return symbol(sym.RETURN);
          }
        case 75: break;
        case 19: 
          { return symbol(sym.RSPAREN);
          }
        case 76: break;
        case 32: 
          { yybegin(YYINITIAL);
          }
        case 77: break;
        case 29: 
          { return symbol(sym.PLUS);
          }
        case 78: break;
        case 48: 
          { return symbol(sym.TRUE);
          }
        case 79: break;
        case 2: 
          { System.out.println("unmatched:"+yytext());
          }
        case 80: break;
        case 49: 
          { return symbol(sym.TYPE);
          }
        case 81: break;
        case 51: 
          { return symbol(sym.CASE);
          }
        case 82: break;
        case 34: 
          { return emptyString();
          }
        case 83: break;
        case 7: 
          { return symbol(sym.IDENTIFIER);
          }
        case 84: break;
        case 26: 
          { return symbol(sym.QUESTION);
          }
        case 85: break;
        case 47: 
          { return symbol(sym.NUM);
          }
        case 86: break;
        case 53: 
          { return symbol(sym.IMPORT);
          }
        case 87: break;
        case 16: 
          { return symbol(sym.LCPAREN);
          }
        case 88: break;
        case 6: 
          { return symbol(sym.MULT);
          }
        case 89: break;
        case 43: 
          { return symbol(sym.NOTEQUALS);
          }
        case 90: break;
        case 40: 
          { return symbol(sym.LTE);
          }
        case 91: break;
        case 14: 
          { return symbol(sym.LPAREN);
          }
        case 92: break;
        case 50: 
          { return symbol(sym.THIS);
          }
        case 93: break;
        case 56: 
          { return symbol(sym.DEFAULT);
          }
        case 94: break;
        case 41: 
          { return symbol(sym.IMPLIES);
          }
        case 95: break;
        case 4: 
          { yybegin(STRING);
          }
        case 96: break;
        case 30: 
          { return symbol(sym.AT);
          }
        case 97: break;
        case 33: 
          { return symbol(sym.CHAR);
          }
        case 98: break;
        case 46: 
          { return symbol(sym.PLUSPLUS);
          }
        case 99: break;
        case 11: 
          { return symbol(sym.MINUS);
          }
        case 100: break;
        case 8: 
          { return symbol(sym.TIDENTIFIER);
          }
        case 101: break;
        case 45: 
          { return symbol(sym.ANDAND);
          }
        case 102: break;
        case 25: 
          { return symbol(sym.TUBE);
          }
        case 103: break;
        case 18: 
          { return symbol(sym.LSPAREN);
          }
        case 104: break;
        case 44: 
          { return symbol(sym.OROR);
          }
        case 105: break;
        case 57: 
          { return symbol(sym.FUNCTION);
          }
        case 106: break;
        case 1: 
          { return symbol(sym.STRING);
          }
        case 107: break;
        case 31: 
          { yybegin(CHAR);
          }
        case 108: break;
        case 22: 
          { return symbol(sym.COMMA);
          }
        case 109: break;
        case 52: 
          { return symbol(sym.FALSE);
          }
        case 110: break;
        case 39: 
          { return symbol(sym.GTE);
          }
        case 111: break;
        case 10: 
          { return symbol(sym.DOT);
          }
        case 112: break;
        case 24: 
          { return symbol(sym.MATCHES);
          }
        case 113: break;
        case 35: 
          { return symbol(sym.DOTDOT);
          }
        case 114: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
