
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 01 15:32:35 CET 2011
//----------------------------------------------------

package testl.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int NUM = 2;
  public static final int MULT = 7;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int IDENTIFIER = 3;
  public static final int LPAREN = 8;
}

